require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('Seed started (SQLite Optimized)...');

  const hashedPassword = await bcrypt.hash('admin123', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@nestory.com' },
    update: {},
    create: {
      email: 'admin@nestory.com',
      password: hashedPassword,
      name: 'Nestory Real Estate Group',
      role: 'BUILDER',
      businessName: 'Nestory Elite Builders',
      phone: '+1 234 567 8900',
      website: 'https://nestory.com',
      experience: '15 Years',
      licenseNumber: 'RE-99201-B',
    },
  });

  await prisma.property.deleteMany({});
  
  const propertyData = [
    {
      title: 'Modern Downtown Loft',
      slug: 'modern-downtown-loft',
      category: 'COMMERCIAL',
      status: 'FOR_SALE',
      price: 1250000,
      currency: 'USD',
      pricePerSqft: 675.67,
      bedrooms: 3,
      bathrooms: 2,
      totalArea: 1850,
      address: '120 Wall Street',
      city: 'New York',
      neighborhood: 'Financial District',
      primaryImage: '/urban_loft_product_1777310504473.png',
      imageGallery: '/urban_loft_product_1777310504473.png',
      internalAmenities: 'AC,Smart Home,High Ceilings',
      externalAmenities: 'Rooftop Access',
      isVerified: true,
      tags: 'Featured,Commercial Ready',
      ownerId: admin.id,
    },
    {
      title: 'Lakeside Villa',
      slug: 'lakeside-villa',
      category: 'RESIDENTIAL',
      status: 'FOR_SALE',
      price: 2850000,
      currency: 'USD',
      pricePerSqft: 890.62,
      bedrooms: 4,
      bathrooms: 3,
      totalArea: 3200,
      address: '450 Lake Tahoe Blvd',
      city: 'Lake Tahoe',
      neighborhood: 'South Shore',
      primaryImage: '/luxury_villa_product_1777309788766.png',
      imageGallery: '/luxury_villa_product_1777309788766.png',
      internalAmenities: 'Fireplace,Heated Floors',
      externalAmenities: 'Private Dock,Garden',
      isVerified: true,
      tags: 'Waterfront,Exclusive',
      ownerId: admin.id,
    },
    {
      title: 'Urban Penthouse',
      slug: 'urban-penthouse',
      category: 'LUXURY',
      status: 'FOR_RENT',
      price: 12000,
      currency: 'USD',
      bedrooms: 2,
      bathrooms: 2,
      totalArea: 1400,
      address: '75 Wardour St',
      city: 'London',
      neighborhood: 'Soho',
      primaryImage: '/modern_penthouse_product_1777309808415.png',
      imageGallery: '/modern_penthouse_product_1777309808415.png',
      communityAmenities: 'Gym,24/7 Security,Concierge',
      isVerified: true,
      tags: 'Luxury Living',
      ownerId: admin.id,
    },
    {
      title: 'Suburban Smart Home',
      slug: 'suburban-smart-home',
      category: 'LUXURY',
      status: 'FOR_SALE',
      price: 4250000,
      currency: 'USD',
      bedrooms: 5,
      bathrooms: 4,
      totalArea: 3750,
      address: '1200 Hamilton Ave',
      city: 'Palo Alto',
      neighborhood: 'Crescent Park',
      primaryImage: '/contemporary_mansion_product_1777309826607.png',
      imageGallery: '/contemporary_mansion_product_1777309826607.png',
      internalAmenities: 'Smart Lighting,EV Charging Ready,Home Theater',
      externalAmenities: 'Infinity Pool,Guest House',
      isVerified: true,
      tags: 'Smart Home,High ROI',
      ownerId: admin.id,
    },
    {
      title: 'Azure Bay Mansion',
      slug: 'azure-bay-mansion',
      category: 'LUXURY',
      status: 'FOR_SALE',
      price: 18500000,
      currency: 'USD',
      pricePerSqft: 1541.67,
      bedrooms: 7,
      bathrooms: 8,
      totalArea: 12000,
      address: '42 Star Island Dr',
      city: 'Miami',
      neighborhood: 'Star Island',
      primaryImage: '/azure_bay_mansion_1777320000000_1777320773587.png',
      imageGallery: '/azure_bay_mansion_1777320000000_1777320773587.png',
      internalAmenities: 'Wine Cellar,Elevator,Gym',
      externalAmenities: 'Private Dock,Infinity Pool,Outdoor Kitchen',
      estimatedROI: 12.5,
      isVerified: true,
      tags: 'Waterfront,Billionaires Row',
      ownerId: admin.id,
    },
    {
      title: 'Alpine Zenith Chalet',
      slug: 'alpine-zenith-chalet',
      category: 'VACATION',
      status: 'FOR_SALE',
      price: 5900000,
      currency: 'CHF',
      bedrooms: 4,
      bathrooms: 4,
      totalArea: 3800,
      address: '12 Chemin des Skieurs',
      city: 'Zermatt',
      neighborhood: 'Matterhorn View',
      primaryImage: '/alpine_chalet_1777320000001_1777320791554.png',
      imageGallery: '/alpine_chalet_1777320000001_1777320791554.png',
      internalAmenities: 'Sauna,Ski Storage,Grand Fireplace',
      externalAmenities: 'Heated Terrace,Jacuzzi',
      isVerified: true,
      tags: 'Ski-In/Ski-Out,Investment',
      ownerId: admin.id,
    },
    {
      title: 'Neo-Tokyo High-Rise',
      slug: 'neo-tokyo-high-rise',
      category: 'RESIDENTIAL',
      status: 'FOR_RENT',
      price: 8500,
      currency: 'USD',
      bedrooms: 1,
      bathrooms: 1,
      totalArea: 950,
      address: '2-1-1 Nihonbashi',
      city: 'Tokyo',
      neighborhood: 'Chuo City',
      primaryImage: '/tokyo_studio_1777320000002_1777320809213.png',
      imageGallery: '/tokyo_studio_1777320000002_1777320809213.png',
      internalAmenities: 'Smart Home Tech,Automated Blinds',
      communityAmenities: 'Rooftop Garden,Tech Lounge',
      isVerified: true,
      tags: 'Tech-Ready,Skyline View',
      ownerId: admin.id,
    },
    {
      title: 'Desert Mirage Villa',
      slug: 'desert-mirage-villa',
      category: 'LUXURY',
      status: 'OFF_PLAN',
      price: 12400000,
      currency: 'AED',
      bedrooms: 6,
      bathrooms: 7,
      totalArea: 8500,
      address: 'Palm Jumeirah',
      city: 'Dubai',
      neighborhood: 'The Fronds',
      primaryImage: '/dubai_mirage_villa_1777320000003_1777320825223.png',
      imageGallery: '/dubai_mirage_villa_1777320000003_1777320825223.png',
      constructionProgress: 45,
      constructionPhase: 'Structure Complete',
      internalAmenities: 'Gold Leaf Details,Marble Flooring',
      externalAmenities: 'Private Beach,Sunken Lounge',
      isVerified: true,
      tags: 'Off-Plan,High Yield',
      ownerId: admin.id,
    },
    {
      title: 'Silicon Hub HQ',
      slug: 'silicon-hub-hq',
      category: 'COMMERCIAL',
      status: 'FOR_SALE',
      price: 24500000,
      currency: 'USD',
      totalArea: 45000,
      address: '500 Sand Hill Rd',
      city: 'Menlo Park',
      neighborhood: 'Tech Corridor',
      primaryImage: '/silicon_hub_1777320000004_1777320844703.png',
      imageGallery: '/silicon_hub_1777320000004_1777320844703.png',
      internalAmenities: 'Fiber Optic Ready,Server Room,Cafeteria',
      communityAmenities: 'EV Charging,Jogging Track',
      isVerified: true,
      tags: 'Prime Commercial,Corporate',
      ownerId: admin.id,
    }
  ];

  for (const data of propertyData) {
    await prisma.property.create({
      data: data,
    });
  }

  console.log('Seed completed successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
